---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compreview-file-cephfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
