---
- hosts: dell
  connection: local
  gather_facts: false

  tasks:
  - name: Update Firm for idrac
    dellemc.openmanage.idrac_firmware:
      idrac_ip:  "{{ idrac_ip }}"
      idrac_user:  "{{ idrac_user }}"
      idrac_password:  "{{ idrac_password }}"
      ignore_cert_warning: yes
      validate_certs: no
      share_name: "http://192.168.127.1/dell2/"
      reboot: True
      job_wait: True
      apply_update: True
      timeout: 300
      catalog_file_name: dell-r650_1.03_Catalog.xml
    register: update_status
  - debug:
      var: update_status