# sua them resouce
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.5
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  # cluster level storage configuration and selection
  storage:
    useAllNodes: false
    useAllDevices: false
    # deviceFilter: sdc
    config:
      metadataDevice:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
    nodes:
    - name: "worker1"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore
      resources:
        limits:
          cpu: "1"
          memory: "1024Mi"
        requests:
          cpu: "1"
          memory: "512Mi"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdc"
      - name: "sdd"
    - name: "worker2"
      resources:
        limits:
          cpu: "1"
          memory: "1024Mi"
        requests:
          cpu: "1"
          memory: "512Mi"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdc"
      - name: "sdd"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore
    - name: "worker3"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore
      resources:
        limits:
          cpu: "1"
          memory: "1024Mi"
        requests:
          cpu: "1"
          memory: "512Mi"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdc"
      - name: "sdd"