global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_hello: AlertManager
  smtp_smarthost: 'mail.cp4d.datalake.vnpt.vn:25'
  smtp_from: 'mail-admin@cp4d.datalake.vnpt.vn'
  smtp_require_tls: false

route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m

  # A default receiver
  receiver: "email"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "telegram"
      group_wait: 10s
      continue: true

receivers:
  - name: "email"
    email_configs:
      - to: 'mail-admin@cp4d.datalake.vnpt.vn'
        from: 'mail-admin@cp4d.datalake.vnpt.vn'
        send_resolved: true

  - name: "slack"
    slack_configs:
    - channel: '#alert-prometheus-slack'
      send_resolved: true
      text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

  - name: "telegram"
    telegram_configs:
    - bot_token: 6206369918:AAEK6Be5BOGq7tc6qcAVIqhB8vHk0LS67_Q
      api_url: https://api.telegram.org
      chat_id: -927765311
      parse_mode: ''
      http_config:
        proxy_url: 'http://10.144.13.144:3129'